---
- name: Initialize Docker Swarm on the first manager
  hosts: Internals
  become: yes
  gather_facts: no
  any_errors_fatal: true

  vars:
    advertise_addr: "{{ ansible_host | default(inventory_hostname) }}"

  tasks:
    - name: Check if node is already part of a swarm
      command: docker info --format '{{ "{{.Swarm.LocalNodeState}}" }}'
      register: swarm_info
      failed_when: false
      changed_when: false

    - name: Initialize swarm on first manager if not already part of a swarm
      command: docker swarm init --advertise-addr {{ advertise_addr }}
      when:
        - inventory_hostname == groups['Internals'][0]
        - swarm_info.stdout != "active"

    - name: Get manager join token
      command: docker swarm join-token -q manager
      register: manager_token
      when: inventory_hostname == groups['Internals'][0]

    - name: Get worker join token
      command: docker swarm join-token -q worker
      register: worker_token
      when: inventory_hostname == groups['Internals'][0]

    - name: Set swarm tokens as facts on all hosts
      set_fact:
        swarm_manager_token: '{{ hostvars[groups["managers"][0]].manager_token.stdout }}'
        swarm_worker_token: '{{ hostvars[groups["managers"][0]].worker_token.stdout }}'
#        run_once: true
#        delegate_to: "{{ item }}"
      with_items: '{{ groups["managers"] + groups["workers"] }}'


 
