---
- hosts: all
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_memtotal_mb
        
    - name: get uptime
      shell: /usr/bin/uptime | grep -ohe 'up .*' | sed 's/,//g' | awk '{ print $2" "$3 }'
      changed_when: False
      register: uptime


    - set_fact: 
        uptime={{ uptime.stdout }}

    - name: Prints two lines of messages, but only if there is an environment value set
      ansible.builtin.debug:
        msg: "Server has been up for {{ uptime }} days"

      
    - debug:
        msg: "Not enough free mem {{ ansible_memtotal_mb }}"
      when: ansible_memtotal_mb < 200
