---
- hosts: all
  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_memtotal_mb
    - debug:
        msg: "Not enough free mem ansibel_memtotal_mb"
      when: ansible_memtotal_mb < 800
