---
- hosts: all
  tasks:
    - name: Get information
      shell: /usr/bin/df --total | tail -n 1
      changed_when: False
      register: inodes
  
    - debug:
        msg: "{{ inodes }} available on {{ HOSTNAME }}"
