---
- hosts: all
  tasks:
    - name: Get information
      shell: /usr/bin/df --total | tail -n 1
      changed_when: False
      register: inodes
    - name: Splitting result
      inodes: "{{ inodes | split }}"
    - debug:
        msg: "1K-blocks: {{ inodes[0] }}  Used {{ inodes[1] }} Available {{ inodes[2] }} Use% {{ inodes[3] }} on {{ HOSTNAME }}"
