---
- hosts: all
  tasks:
    - name: Get information
      ansible.builtin.debug:
       info: "this is a line"
       arr: "{{ info.split(' ') }}"
  
    - debug:
        msg: "{{ arr[0] }} available on {{hostname}}"
