---
- hosts: all
  tasks:
    - name: Get information
      shell: /usr/bin/df -ih
      changed_when: False
      register: inodes
  
    - debug:
        msg: "{{ inodes }} available on {{ HOSTNAME }}"
