---
- hosts: all
  tasks:
    - name: Get information
      set_fact:
       - tekst: "this is a line"
       - arr: "{{ tekst.split(' ') }}"
  
    - debug:
        msg: "{{ arr[0] }} available on {{hostname}}"
