---
- hosts: all
  tasks:
    - name: Get info on bloks
      shell: /usr/bin/df --total | tail -n 1
      changed_when: False
      register: bloks
    - name: Splitting result
      set_fact:
        bloks: "{{ bloks.stdout | split }}"

    - name: Get info on inodes
      shell: /usr/bin/df  / -i | tail -n 1
      changed_when: False
      register: inodes
    - name: Splitting result
      set_fact:
        inodes: "{{ inodes.stdout | split }}"
    - debug:
        msg: 
        - "Total inodes: {{ inodes[1] }}  Used {{ inodes[2] }} Available {{ inodes[3] }} Use% {{ inodes[4] }} on {{ HOSTNAME }} "
        - "Total 1K-blocks: {{ bloks[1] }}  Used {{ bloks[2] }} Available {{ bloks[3] }} Use% {{ bloks[4] }} on {{ HOSTNAME }}"
        - "Getting number {{ inodes[4][:-1] }} "
        - " {{ Task[id] }} "
