---
- hosts: all
  tasks:
    - name: Get info   
      info: "this is a line"
      arr: "{{ string.split('=') }}"
      inodes: "{{ arr[0] }} available on {{hostname}}"
    - debug:
      msg: "{{inodes}}"
