---
- hosts: all
  tasks:
    - name: Get information
      vars:
       tekst: "this is a line"
      vars:
       arr: "{{ tekst.split(' ') }}"
  
    - debug:
        msg: "{{ arr[0] }} available on {{hostname}}"
