---
- name: Install Docker on Debian nodes
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    docker_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Add GPG key
      ansible.builtin.shell:
        cmd: |
          sudo install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          sudo chmod a+r /etc/apt/keyrings/docker.gpg

    - name: Add the repository to Apt sources
      block:
        - name: Add repos
          ansible.builtin.shell:
            cmd: |
               echo \
               "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
               "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
               sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: Install Docker Engine and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group (optional)
      user:
        name: "{{ ansible_user | default('root') }}"
        groups: docker
        append: yes
      when: ansible_user != 'root'
