---
- name: Install Docker on Debian nodes
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    docker_packages:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  tasks:
    - name: Ensure required packages are installed
      apt:
        name: "{{ docker_packages }}"
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_facts['lsb']['codename'] }} stable"
        state: present
        filename: docker

    - name: Install Docker Engine and plugins
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group (optional)
      user:
        name: "{{ ansible_user | default('root') }}"
        groups: docker
        append: yes
      when: ansible_user != 'root'
