---
- name: check if system reboot is required
  hosts: all
  become: yes
  tasks:
    - name: check if system reboot is required
      become: true
      msg: "OK"
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - debug:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
- name: Setting stats (not aggregating)
  ansible.builtin.set_stats:
    data:
      the_answer: msg
    aggregate: no
