---
- name: check if system reboot is required
  hosts: all
  become: yes
  tasks:
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: send message to discord on reboot required
      uri:
        url:  "{{ WEB_HOOK }}"
        method: 'POST'
        body_format: json
        body: {
           'content': "Reboot needed {{ HOSTNAME }}",
           'username': "You humble servant",
        }
        status_code: 204  
      when: reboot_required.stat.exists  
    - name: Setting failed state on reboot required
      ansible.builtin.fail:
        msg: "Reboot is required"
      when: reboot_required.stat.exists
