---
- name: check if system reboot is required
  hosts: all
  become: yes
  tasks:
    - name: check if system reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required
    - name: send message to discord on reboot required
      uri:
        url:  "{{ WEB_HOOK }}"
        method: 'POST'
        body_format: json
        body: {
           'content': "{{ HOSTNAME }} Reboot needed",
           'username': "You humble servant",
        }
        status_code: 204  
      when: reboot_required.stat.exists  
    - name: Setting failed state on reboot required
      ansible.builtin.fail:
        msg: "{{ HOSTNAME }} Reboot is required"
      when: reboot_required.stat.exists
    - debug:
        msg: "{{ ansible_play_hosts | map('extract', hostvars, 'date_res') | map(attribute='stdout') | list }}"
      run_once: yes
