---
- hosts: all
  
  tasks:
    - name: packages | ensure apt list dir exists
      file:
        path: /var/lib/apt/lists/
        state: directory
        mode: 0755
    - name: APT Package List Updater
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: APT Package Upgrader
      become: true
      apt:
        upgrade: yes
