---
- hosts: all
  
  tasks:
    - name: APT Package List Updater
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: APT Package Upgrader
      become: yes
      become_method: sudo
      apt:
        upgrade: yes
      register: result
    - name: List installed and updated packages
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) ' /var/log/dpkg.log' "
      register: result
    - name: Show Output
      debug: msg="{{ result.stdout_lines }}"
      when: result.changed
    - name: send message to discord on reboot required
      uri:
        url:  "{{ WEB_HOOK }}"
        method: 'POST'
        body_format: json
        body: {
           'content': "Opdated software on {{ HOSTNAME }}",
           'username': "You humble servant",
        }
        status_code: 204  
      when: result.changed  
