- hosts: all
  tasks:
    - name: Send Discord Message - Basic
      uri:
        url:  "{{ WEB_HOOK }}"
        method: 'POST'
        body_format: json
        body: {
           'content': "Panik panik",
           'username': "The bad man",
           'avatar_url': "<SOME URL TO AN AVATAR>"
         }
